version: '3.8'

services:
  nutriplan-app:
    image: nutriplan-app:previous-stable
    container_name: nutriplan-app
    ports:
      - '3001:3000'
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: nutriplan-mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: